name: autofix.ci

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup pnpm
        uses: pnpm/action-setup@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24.11
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Prepare development build
        run: pnpm dev:prepare

      - name: Format code
        run: pnpm fmt

      - uses: autofix-ci/action@c5b2d67aa2274e7b5a18224e8171550871fc7e4a
        with:
          commit-message: "chore: apply automated updates"
